name: Mine data

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:

  build:
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
      statuses: write
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '20.x'
      - name: Install dependencies
        run: |
          npm install puppeteer
      - name: Run script
        run: |
         apt-get update
         apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2
          libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4
          libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0
          libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1
          libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1
          libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release
          xdg-utils wget
          node ./src/scrapeChunks.js

      - name: set email
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: commit
        run: |
            git add --all
            git commit -am "✨ Chunks updated!" 
            git push
      